### ISSUE TITLE
How would i change de locale?

### ISSUE THREAD

**Issue by gablemos-zz** [esausilva/fullcalendar-aspnet-core#1]
I would like to change the locale, and maybe other configurations. Were should i do it?

I tryed to do it on Scripts/calendar.js:
```
 $('#calendar').fullCalendar({
    defaultView: 'month',
    height: 'parent',
    locale: 'pt',
    ...
 });
```
Then i run webpack, but it did not work.

**Comment by esausilva** [comment]
Hi Gabriel, following the FullCalendar [documentation](https://fullcalendar.io/docs/v3/locale) for locale, you would need to include the locale JS data file. You can get the CDN link [here](https://cdnjs.com/libraries/fullcalendar/3.9.0)

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/locale/pt-br.js"></script>
```

Note: I'm linking documentation for v3 since that is the one I'm using in the project, if you updated to v4 then you would need to change to v4 documentation.
